---
application:
  name: "binge-companion-api"
  project: "superhero-tv-trivia-api"
  organization: "QoveryCommunity"
databases:
- type: "POSTGRESQL"
  name: "superhero-tv-trivia"
  version: "11"
routers:
- name: "main-binge-companion-api"
  routes:
  - application_name: "binge-companion-api"
    paths:
    - "/*"
